
###
POST http://localhost:3001/api/inventory/update
Content-Type: application/json

{
    "quantity": 23,
    "part_id": 1
}

###

POST http://localhost:3001/api/inventory/new
Content-Type: application/json

{
    "quantity": 0,
    "part_id": 1
}

###

GET http://localhost:3001/api/test/part-by-number
Content-Type: application/json

{
    "number": 1
}

###

POST http://localhost:3001/api/inventory/new
Content-Type: application/json

{
    "part_id": 149,
    "quantity": 0
}
